grammar = { EOF } | module exports statement grammar

module = "module" identifier ";"

exports = { empty } | "export" identifier exports

statement = section | constant | instruction

section = "section" { identifier } ";"
constant = tag literal ";"
instruction = tag? opcode operand* ";"

tag = { identifier } ":"
literal = { integer }
opcode = { identifier }
operand = { identifier }