grammar = { EOF } | statement grammar
statement = section | constant | instruction
section = "." { identifier } ";"
constant = tag literal ";"
instruction = tag? opcode operand* ";"
tag = { identifier } ":"
literal = { integer }
opcode = { identifier }
operand = { identifier }