name: hasky
version: 0.1.0
github: "sharpvik/hasky"
license: MIT
author: "Viktor A. Rozenko Voitenko, Aleksei Martirosov"
maintainer: "sharpvik@gmail.com"
copyright: "2021 Hasky Authors"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: Haskell-based functional programming language
category: Functional Programming Languages
description: Please see README.md on GitHub at <https://github.com/sharpvik/hasky#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: lib
  build-tool-depends: alex:alex #, happy:happy
  dependencies:
    - array
    - data-default

executables:
  hasky:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hasky

tests:
  hasky-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hasky
      - directory
      - filepath
      - tasty
      - data-default
      - tasty-hunit
